package com.rl.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2019-11-13T15:33:26.444+08:00
 * Generated source version: 3.2.11
 *
 */
@WebService(targetNamespace = "http://service.ws.ecps.rl.com/", name = "EbWSItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWSItemService {

    @WebMethod
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.ecps.rl.com/", className = "com.rl.ecps.stub.PublishItem")
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.ecps.rl.com/", className = "com.rl.ecps.stub.PublishItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String publishItem(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
